name: Build PDF document
run-name: Build ${{ github.actor }} PDF document
on: 
  push:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  build:    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get current date
        run: echo "CUR_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Get current year
        run: echo "CUR_YEAR=$(date +'%Y')" >> $GITHUB_ENV
      - name: Build pdf
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume.tex
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
            name: resume-mcc-${CUR_DATE}
            path: resume.pdf
